/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { EmployeeCreateNestedManyWithoutProjectsInput } from "./EmployeeCreateNestedManyWithoutProjectsInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { EnumProjectStatus } from "./EnumProjectStatus";
import { TaskCreateNestedManyWithoutProjectsInput } from "./TaskCreateNestedManyWithoutProjectsInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";

@InputType()
class ProjectCreateInput {
  @ApiProperty({
    required: false,
    type: () => EmployeeCreateNestedManyWithoutProjectsInput,
  })
  @ValidateNested()
  @Type(() => EmployeeCreateNestedManyWithoutProjectsInput)
  @IsOptional()
  @Field(() => EmployeeCreateNestedManyWithoutProjectsInput, {
    nullable: true,
  })
  createdBy?: EmployeeCreateNestedManyWithoutProjectsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  identifier?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumProjectStatus,
  })
  @IsEnum(EnumProjectStatus)
  @IsOptional()
  @Field(() => EnumProjectStatus, {
    nullable: true,
  })
  status?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  statusDetails?: string | null;

  @ApiProperty({
    required: false,
    type: () => TaskCreateNestedManyWithoutProjectsInput,
  })
  @ValidateNested()
  @Type(() => TaskCreateNestedManyWithoutProjectsInput)
  @IsOptional()
  @Field(() => TaskCreateNestedManyWithoutProjectsInput, {
    nullable: true,
  })
  tasks?: TaskCreateNestedManyWithoutProjectsInput;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  timeline?: InputJsonValue;
}

export { ProjectCreateInput as ProjectCreateInput };
