/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ProjectCreateNestedManyWithoutEmployeesInput } from "./ProjectCreateNestedManyWithoutEmployeesInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { DepartmentWhereUniqueInput } from "../../department/base/DepartmentWhereUniqueInput";
import { TaskCreateNestedManyWithoutEmployeesInput } from "./TaskCreateNestedManyWithoutEmployeesInput";

@InputType()
class EmployeeCreateInput {
  @ApiProperty({
    required: false,
    type: () => ProjectCreateNestedManyWithoutEmployeesInput,
  })
  @ValidateNested()
  @Type(() => ProjectCreateNestedManyWithoutEmployeesInput)
  @IsOptional()
  @Field(() => ProjectCreateNestedManyWithoutEmployeesInput, {
    nullable: true,
  })
  assignedTo?: ProjectCreateNestedManyWithoutEmployeesInput;

  @ApiProperty({
    required: false,
    type: () => DepartmentWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DepartmentWhereUniqueInput)
  @IsOptional()
  @Field(() => DepartmentWhereUniqueInput, {
    nullable: true,
  })
  department?: DepartmentWhereUniqueInput | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  email!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phoneNumber?: string | null;

  @ApiProperty({
    required: false,
    type: () => TaskCreateNestedManyWithoutEmployeesInput,
  })
  @ValidateNested()
  @Type(() => TaskCreateNestedManyWithoutEmployeesInput)
  @IsOptional()
  @Field(() => TaskCreateNestedManyWithoutEmployeesInput, {
    nullable: true,
  })
  tasks?: TaskCreateNestedManyWithoutEmployeesInput;
}

export { EmployeeCreateInput as EmployeeCreateInput };
